from django import forms
from Mehraneh.choices import *

class BenefactorRegistraton(forms.Form):
    name = forms.CharField()
    surname = forms.CharField()
    nickname = forms.CharField()
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    rpassword = forms.CharField(widget=forms.PasswordInput)
    sex = forms.ChoiceField(choices=SEX_CHOICES, required=True)
    birthDate = forms.IntegerField()
    birthMonth = forms.IntegerField()
    birthYear = forms.IntegerField()
    education = forms.ChoiceField(choices=EDUCATION_CHOICES, required=True)
    major = forms.CharField()
    nid = forms.CharField()
    city = forms.ChoiceField(choices=CITY_CHOICES, required=False)
    address = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField()
    image = forms.ImageField(required=False)
    ability = forms.MultipleChoiceField(choices=ABILITY_CHOICES)
    more = forms.CharField(widget=forms.Textarea, required=False)
    terms = forms.BooleanField(required=True)

class OrganizationRegistration(forms.Form):
    name = forms.CharField()
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    rpassword = forms.CharField(widget=forms.PasswordInput)
    registrationDate = forms.IntegerField()
    registrationMonth = forms.IntegerField()
    registrationYear = forms.IntegerField()
    city = forms.ChoiceField(choices=CITY_CHOICES, required=False)
    address = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField()
    website = forms.URLField()
    license = forms.CharField()
    logo = forms.ImageField(required=False)
    more = forms.CharField(widget=forms.Textarea, required=False)
    thursdays = forms.BooleanField(required=False)
    fridays = forms.BooleanField(required=False)
    terms = forms.BooleanField(required=True)

